[programs.localnet]
anchor_escrow = "Ha9BXm9aGDU3Vyv3D2nvF2cMM2vMo1RqUiyEeL67smpP"

[registry]
url ="http://127.0.0.1:8899"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
