[programs.localnet]
anchor_escrow = "4NVK3ABAU9tyF4eENdN7ZE9fTZH1dmLaEhknt5mgtYuE"

[registry]
url ="http://127.0.0.1:8899"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
