[programs.localnet]
anchor_escrow = "6DAH49WWWrpGREtQfgVZNTj7nWAFJXqn3ub3gemtKsLf"

[registry]
url ="http://127.0.0.1:8899"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
