[programs.localnet]
anchor_escrow = "6GmDMEb2ETfCUmFDcmhHDpyeEy4AeMeA2unRowUrt3eo"

[registry]
url ="http://127.0.0.1:8899"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
