[programs.localnet]
anchor_escrow = "H4r9Vgfa9F9FaNUh8tkqQGQAtbaFkLBoPUHsiaou6fNj"

[registry]
url ="http://127.0.0.1:8899"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
